export class OrderItem {
    id?: string;         // Optional, as it might be generated by MongoDB
  orderId!: string;
  productId!: string;
  productName!: string;
  price!: number;
  quantity!: number;
  vendorId!: string;
}
